### ISSUE TITLE
Streamdeck-ui does not handle waking up from sleep properly.

### ISSUE THREAD

**Issue by flajann2** [timothycrosley/streamdeck-ui#155] opened 2021-08-24 06:08 UTC
Whenever I wake up my computer from sleep, Streamdeck fails with this message:

/usr/lib/python3.9/site-packages/streamdeck_ui/api.py:135: UserWarning: A Could not open HID device. error occurred when trying to reconnect to CL49J1A0179323:49:33
  warn(f"A {error} error occurred when trying to reconnect to {deck_serial}")
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 472, in sync
    api.ensure_decks_connected()
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/api.py", line 143, in ensure_decks_connected
    render()
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/api.py", line 312, in render
    deck.set_key_image(button_id, image)
  File "/usr/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 192, in set_key_image
    self.device.write(payload + padding)
  File "/usr/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 430, in write
    return self.hidapi.write(self.device_handle, payload)
  File "/usr/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 279, in write
    raise TransportError("Failed to write out report (%d)" % result)
StreamDeck.Transport.Transport.TransportError: Failed to write out report (-1)

System:
OS: Arch Linux x86_64
Kernel: 5.13.12-arch1-1
Uptime: 1 day, 19 hours, 40 mins
Packages: 1592 (pacman), 13 (flatpak)
Shell: bash 5.1.8
Resolution: 1440x2560, 1440x2560, 3840x2160
DE: Plasma 5.22.4
WM: KWin
WM Theme: QTStepGradientRC319p
Theme: ArchSmooth [Plasma], Breeze [GTK2/3]
Icons: [Plasma], Tela [GTK2/3]
Terminal: tmux
CPU: AMD Ryzen Threadripper 3970X (64) @ 3.700GHz
GPU: NVIDIA GeForce RTX 3080 Ti
Memory: 104553MiB / 257591MiB

**Comment by dodgyrabbit** [comment] 2021-09-16 02:37
Closing as duplicate of #4

**Closed by dodgyrabbit** 2021-09-16 02:37 UTC
Labels: bug, duplicate
