### ISSUE TITLE
Request: Support for more characters in Write Text

### ISSUE THREAD

**Issue by tintinmaster** [timothycrosley/streamdeck-ui#60] opened 2020-07-24 16:22 UTC
I wanted to make a button to type ¯\_(ツ)_/¯ , but apparently these characters are not supported.
The resulting text was: ¯UV()VI¯

**Comment by dodgyrabbit** [comment] 2021-03-28 03:54
Closing as duplicate of #85

**Closed by dodgyrabbit** 2021-03-28 03:54 UTC
Labels: bug, duplicate
