### ISSUE TITLE
Is there a way or example of how to use the API via our own scripts?

### ISSUE THREAD

**Issue by lukaswelinder** [timothycrosley/streamdeck-ui#142] opened 2021-07-05 20:06 UTC
Is there a way to import and interact with the API in our own scripts?

If so, adding an example of how to the docs would be handy. This could help with issues like #99 and several others relating to dynamic/programatic changes to buttons.

If this is not currently possible, making it so would make this tool much more flexible, and open up the possibility of community created plugins/cookbooks.

**Comment by lukaswelinder** [comment] 2021-07-05 23:00
After experimenting a bit, it looks like this isn't really supported. Executing the API while streamdeck-ui is running fails to connect to device or causes other weird issues. The best solution I have found is to run it via my own wrapper script that calls `gui.start()` then uses the API from there.

I have not yet attempted to inject my own keypress handler. I'm wondering if a better approach would be a websocket server that can be interacted with via command line. Open to ideas, I'll be playing around with this idea when I have some spare time next weekend.

**Comment by dodgyrabbit** [comment] 2021-09-16 02:59
There is currently no good way to do this. There are some potential options - websocket could work. Maybe DBus messaging. Perhaps easier to build that into the CLI and it can use some form of IPC to notify the main app what to do.

**Comment by gregfr** [comment] 2021-10-21 07:05
What about just plain old REST endpoint?

**Comment by dodgyrabbit** [comment] 2022-02-24 22:25
Duplicate of #99

**Closed by dodgyrabbit** 2022-02-24 22:25 UTC
Labels: enhancement
