### ISSUE TITLE
Keypress's not registered?

### ISSUE THREAD

**Issue by SumNeuron** [timothycrosley/streamdeck-ui#202] opened 2022-02-13 23:50 UTC
Once `streamdeck` is running sometimes a button press is registered as "Action [A-O]" however more often than not it is not registered as anything. This can be frustrating when trying to sync this with another happen that records keypresses to assign hotkeys in that program. Are there workarounds?

**Comment by dodgyrabbit** [comment] 2022-02-14 14:16
Can you provide steps to reproduce this?
Config file would be useful.
Operating system version, python version.
Can you elaborate what this means: is registered as "Action [A-O]"

> this with another happen that records keypresses to assign hotkeys in that program.

I don't understand this sentence.  Sync this with another _happen_?

**Comment by dodgyrabbit** [comment] 2022-02-14 18:38
Thanks for the additional details, but I'm having a hard time understanding the issue. 
Can you provide a screenshot your streamdeck-ui button config?
![image](https://user-images.githubusercontent.com/518187/153924390-2bde4527-0856-43ad-9144-ace4aad2e972.png)

> Basically some apps have "record keypress" options for setting hotkeys,
> some have, like this program, text based variants (eg "ctrl+F2"). I want to
> be able to have streamdeck keypresses be picked up by these applications,
> which right now they are not doing.

Typically you setup the key sequence in the other app, and the configure streamdeck-ui to send those keys. Maybe that's what you're saying here.

Just a hunch - but do you happen to know if you are using Wayland for your display server? The library we used (pynput) has known issues with Wayland and is unable to send keys to other applications. This is due to more security that was added to the display server.

Some shortcuts are known not to work, even on X
https://github.com/timothycrosley/streamdeck-ui#known-issues

**Comment by dodgyrabbit** [comment] 2022-02-23 14:34
@SumNeuron Any more info on this, how to reproduce?

**Comment by SumNeuron** [comment] 2022-02-24 21:35
@dodgyrabbit sorry for the delay. The configure is just Like that above. My point is, some applications let you register hotkeys by listening to what key is pressed. When I press a key on the streamdeck, no button is registered.

**Comment by dodgyrabbit** [comment] 2022-02-24 21:40
I do not see any actionable items here. There simply is not enough information for me to do anything. 
Should we close this case or do you feel something can be done? My sense is that you discovered "this doesn't work with some apps". I don't know what else to do about that.

**Comment by dodgyrabbit** [comment] 2022-02-26 19:12
FYI you can now send hex symcodes. Please see documentation in case it's relevant.

**Closed** 2022-02-26 19:11 UTC
Labels: question
