### ISSUE TITLE
UI in Linux Mint Cinnamon not working

### ISSUE THREAD

**Issue by uvulpos** [timothycrosley/streamdeck-ui#84] opened 2020-12-25 23:32 UTC
Hey there,
My Linux Mint 20 Cinnamon Machine (Huawei Matebook X Pro 2018) has a problem displaying your inputs. It's too small. I don't know which Desktop Framework you used, maybe it's something I miss configured but I can't work with this. Maybe it would be a solution to make it resizable?  

![Image](https://i.imgur.com/h6oC3D2.png)

**Comment by desrod** [comment] 2020-12-26 19:14
What happens if you prefix your launch command with `QT_AUTO_SCREEN_SCALE_FACTOR=0` and alter the factor to suit your UI's controls and environment?

**Comment by uvulpos** [comment] 2020-12-26 20:50
Nope, nothing changed 😕

**Comment by uvulpos** [comment] 2020-12-26 22:22
I managed somehow to insert click events by copying them into the input fields, reading them in the UI is not possible, but they seem to work. I leave this ticket still open because this is just an awful workaround

**Comment by desrod** [comment] 2020-12-26 22:26
You might want to file a bug with your Linux distribution, giving them specifics about your version and other related dependencies. I'm just an end-user of streamdeck, but I can't reproduce your results.

**Comment by dodgyrabbit** [comment] 2021-03-22 16:45
@uvulpos Can you confirm this is still an issue?  If so, we'll need your help to narrow down what is going wrong. 
Maybe the basics first - is the OS up to date with latest patches/updates. 

A shot in the dark, but on a brand new Ubuntu Linux install, I had to install
```
sudo apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
```
In order to correctly load the Qt platform plugin "xcb".

**Comment by uvulpos** [comment] 2021-03-23 08:06
Yes, still a problem 😄

**Comment by dodgyrabbit** [comment] 2021-03-23 16:30
I suspect the issue is related to the DPI on your Huawei Matebook X Pro 2018  since it has a 3000 x 2000 screen resolution.

By manually forcing this setting:
![display-settings](https://user-images.githubusercontent.com/518187/112181547-ebc6cf00-8bd2-11eb-8145-2649d15fa68a.png)
I managed to reproduce something similar.

Perhaps you can experiment with some of the display settings and see if what works, what doesn't and post your findings here.
You have to exit and restart streamdeck-ui after you make a display setting change.

**Comment by dodgyrabbit** [comment] 2021-03-23 16:51
You can try the following:
``` console
$ export QT_AUTO_SCREEN_SCALE_FACTOR=1
```
Then launch
``` console
$ streamdeck
```

There are some other settings to try here:
https://doc.qt.io/qt-5/highdpi.html

**Comment by uvulpos** [comment] 2021-03-23 20:49
Nein, funktioniert nicht 😕

**Comment by uvulpos** [comment] 2021-03-23 20:50
Ich werde das System in einem halben Jahr sowieso ausmustern, ich hoffe dann habe ich diesen Bug nicht mehr 🤔

**Comment by dodgyrabbit** [comment] 2021-03-24 03:06
Closing this is not reproducible. If you are able to spend some time and share more details on this problem and narrow it down, please reopen. Better yet, submit a PR to fix!
Thank you.

**Closed by dodgyrabbit** 2021-03-24 03:06 UTC
Labels: bug, help wanted, wontfix
