### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by pcolonna** [timothycrosley/streamdeck-ui#51] opened 2020-06-01 09:22 UTC
Hi everyone,

I'm running a freshly installed ubuntu 20.04 except for Anaconda and a few python packages. 
I installed streamdeck-ui following the steps on the readme, add it to my path following instructions in issue #21 

When i try to run streamdeck, i got the following message

> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Aborted (core dumped)

I tried uninstalling and re-install everything, but it didn't change anything.  
I installed xcb with  

> sudo apt install xcb

still no changes. 

I'm looking into re-installing Qt but no luck yet.

Any idea? Thank you very much!

**Comment by bertabus** [comment] 2020-06-25 21:45
I was getting the same error on ubuntu 20.04 and finally got it to run using the below command 

```sh
sudo apt install --reinstall libxcb-xinerama0
```

**Comment by dodgyrabbit** [comment] 2021-03-30 01:12
Hi @pcolonna and @bertabus I can confirm the issue you are experiencing. Detailing it here in case it's useful to someone:

The pyside2 python package (5.15.2) is supposed to install QT5 and things should just work. However, on Debian based systems like Ubuntu, there is an issue with a missing library.

https://bugreports.qt.io/browse/PYSIDE-1473
Workaround (same as per @bertabus):
https://forum.qt.io/topic/116347/fresh-install-5-15-could-not-load-the-qt-platform-plugin-xcb

As a side note, [README.txt](https://github.com/timothycrosley/streamdeck-ui/tree/db4dc28441b548f6208689fa1cc650c7f8673ad5) and install in [scripts/ubuntu_install.sh](https://github.com/timothycrosley/streamdeck-ui/blob/722a7cf36b161503526300f3bb49d7b89f8ff72b/scripts/ubuntu_install.sh) diverged a bit in the past, so depending which method you used, you would have either explicitly installed QT5 (using the script) or not (using the readme).

While we're waiting for PySide2 v5.15.3 to be released, I've updated the scripts for Debian/Ubuntu to install only the missing package. 

Closing this issue.

**Closed by dodgyrabbit** 2021-03-30 01:12 UTC
Labels: bug, documentation

**Comment by jolinux** [comment] 2021-06-10 08:13
Hello, thanks for answer. But 

I do 
sudo apt install --reinstall libxcb-xinerama0

Error is the same

I download the script (copy/paste) start the script as sudo and user . Script install something or not (because the system has the files before installed)

The print
############################################
 echo 'Installing libraries'
Installing libraries
+ sudo apt install qt5-default libhidapi-hidraw0 libudev-dev libusb-1.0-0-dev python3-pip
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libhidapi-hidraw0 ist schon die neueste Version (0.8.0~rc1+git20140818.d17db57+dfsg-2).
libusb-1.0-0-dev ist schon die neueste Version (2:1.0.22-2).
python3-pip ist schon die neueste Version (18.1-5).
qt5-default ist schon die neueste Version (5.11.3+dfsg1-1+deb10u4).
libudev-dev ist schon die neueste Version (241-7~deb10u7).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  gir1.2-keybinder-3.0 libkeybinder-3.0-0 python-glade2 python-gst-1.0
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
+ echo 'Adding udev rules and reloading'
Adding udev rules and reloading
++ whoami
+ sudo usermod -a -G plugdev jo
+ sudo tee /etc/udev/rules.d/99-streamdeck.rules
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", MODE:="666", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", MODE:="666", GROUP="plugdev"
+ sudo udevadm control --reload-rules
+ echo 'Unplug and replug in device for the new udev rules to take effect'
Unplug and replug in device for the new udev rules to take effect
+ echo 'Installing streamdeck_ui'
Installing streamdeck_ui
+ pip3 install --user streamdeck_ui
Requirement already satisfied: streamdeck_ui in ./.local/lib/python3.8/site-packages (1.1.2)
Requirement already satisfied: pyside2<6.0,>=5.13 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (5.15.2)
Requirement already satisfied: streamdeck<0.9.0,>=0.8.4 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (0.8.4)
Requirement already satisfied: pillow<9.0,>=8.2 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (8.2.0)
Requirement already satisfied: pynput<2.0,>=1.7 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (1.7.3)
Requirement already satisfied: python3-xlib<0.16,>=0.15 in ./.local/lib/python3.8/site-packages (from streamdeck_ui) (0.15)
Requirement already satisfied: evdev>=1.3 in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (1.4.0)
Requirement already satisfied: six in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (1.16.0)
Requirement already satisfied: python-xlib>=0.17 in ./.local/lib/python3.8/site-packages (from pynput<2.0,>=1.7->streamdeck_ui) (0.30)
Requirement already satisfied: shiboken2==5.15.2 in ./.local/lib/python3.8/site-packages (from pyside2<6.0,>=5.13->streamdeck_ui) (5.15.2)
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python3.8 -m pip install --upgrade pip' command.
+ echo 'If the installation was successful, run '\''streamdeck'\'' to start.'
If the installation was successful, run 'streamdeck' to start.
#######################################################################



Error is the same.  Debian 10 Buster is not Ubuntu -))   No idea  to fix a Debian system ??

Which  lib is the problem ?

Hope a user has a solution

**Comment by brentpicasso** [comment] 2024-08-04 06:11
If anyone is still having problems, this may help: 

```
sudo apt-get install libxcb-cursor0
```
