### ISSUE TITLE
Dimming issues

### ISSUE THREAD

**Issue by My1** [timothycrosley/streamdeck-ui#265] opened 2022-09-19 13:51 UTC
**Describe the bug**
Basically it always dims to fully Black regardless of the dim setting and comes back to full brightness

**To Reproduce**
1. set a Dimming brightness that is not zero
3. wait till it's dark
4. Press a button to wake it up
5. See error

**Expected behavior**
1) the dimming brightness should be according to the setting
2) it should return to the main brightness

**Operating system (please complete the following information)**
 - OS: Kubuntu 22.04 LTS
 - Desktop environment: Kubuntu
 - Python version: 3.10.4

**Stream Deck Version**
MK2

Side note: the dimming brightness in the dialog also gets lowered everytime you click okay and re-open the dialog, not sure if related.

**Comment by dodgyrabbit** [comment] 2022-09-24 03:47
Please try version `2.0.6` to see if it resolves your problem.

```
pip install streamdeck_ui --upgrade
```

**Comment by My1** [comment] 2022-09-26 10:43
seems a bit better, the dim bar doesnt go down on every OK, but it seems to dim lower than the same brightness set normally.

![image](https://user-images.githubusercontent.com/6696524/192257288-f9a3d506-d5b2-43f1-9808-b3926714bfbb.png)

on this it still goes fully dark but if i set the upper bar to the same value there's still suff visible.

**Comment by dodgyrabbit** [comment] 2022-09-26 12:57
I think you have a misunderstanding of how it is supposed to work.

The second slider dims to a **percentage** of the first (not an absolute value). I.e. if you want it to go down by half, then you should have the second slider half way.

Because your primary brightness is quite low, a small percentage value of that would be near 0.
So raise the second slider a bit.

I think it may make sense to actually preview the "effective" brightness to make this a bit less confusing.

**Comment by My1** [comment] 2022-09-26 13:14
oh I thought percent referred to percent of total brightness

**Comment by dodgyrabbit** [comment] 2022-09-26 16:14
This behaviour is also "by design". If it dim low enough (below 20) then you need two presses. The first to "wake up" the display, the second to trigger the action.

The reason for this is that below 20 brightness you basically can't see which icon you are pressing. We don't want to trigger an action unless the display is "on" or at least sufficiently bright that you're not pressing a key by mistake.

So try making the dim setting a bit higher and it will only take one press. 

This behaviour is not well explained in the user interface, so I can understand why this may seem confusing.

**Comment by My1** [comment] 2022-09-26 16:20
I know that already from stream deck sleep mode on windows. but that's not what I mean. I have currently set it to 10 seconds to go dim. which it does, but several minutes later, it goes fully black.

and after that you need to press twice (1st to get to dim level, 2nd to full brightness) and THEN you can do an action on the third press

**Comment by dodgyrabbit** [comment] 2022-09-26 21:06
This software (streamdeck ui) only has one dim level and dims the screen when the configured timeout happens.

If it turns off completely a few minutes after the dimming happened, this behaviour is outside the control and design of this software. Is your computer going into sleep mode, or are you saying that the computer does not suspend/sleep -  yet the stream deck _turned off_? Does it respond to keypresses on the stream deck itself when in this state? This does not make sense if the computer was suspended, as it shuts off power to USB devices and therefore it won't respond to keypresses.

The only other explanation I can think of: maybe something new in the MK2 firmware (i.e. the streamdeck itself will sleep), which happens independently of the software. I don't have the MK2 (original 15 key), so thats one difference.

**Comment by My1** [comment] 2022-09-26 21:09
the computer stays on normally. and the steam deck goes on. maybe this could because of the settings I had in windows prior to going into linux, not sure tbh.

but yeah the stream deck will respond to a key to wake it up again

**Comment by My1** [comment] 2022-09-27 11:46
if you connect your streamdeck to a windows do you get this kinda "standby after" option?
![image](https://user-images.githubusercontent.com/6696524/192517042-741fdc38-a68e-45c5-a19d-c4009bf5eb0f.png)

**Comment by dodgyrabbit** [comment] 2022-09-27 19:22
I can confirm the behaviour you describe.

If you set your Stream Deck to have a 5 minute sleep mode timeout in the original software on Windows, this timeout is programmed into the device and will still have an effect when running it under Linux machine. Note that it seems to clear this behaviour if you _physically unplug and plug it back in_. We can deduce it is storing this configuration on the device, in volatile memory (as opposed to flash memory or something).

Can you confirm _how_ you moved between Linux and Windows? Are you using VMs or perhaps a powered hub? Normally I would expect if you unplugged it from a Windows machine and plugged it into a Linux machine you will not have this problem since power would have been lost.

BTW This Linux Stream Deck UI software cannot detect or control this configuration. It may need to be reverse engineered by https://github.com/abcminiuser/python-elgato-streamdeck to add support for that.

I'm closing this case as there is no specific further actions to take here and the original bug reported was fixed.

**Closed by dodgyrabbit** 2022-09-27 19:22 UTC
Labels: bug

**Comment by My1** [comment] 2022-09-27 19:37
Yeah i have the stream deck on my monitor so that pretty likely acts as a powered hub when rebooting between windows and linux. Regarding the thing being volatile, cool to know, can be something i can test.

Maybe worth a doc note or whatever, but - good to know nothing's actually broken

**Comment by Danie10** [comment] 2023-07-18 14:24
This was a really useful explanation above (yes, probably needs to be in the readme docs too) regarding the dimming being a percentage of the standard brightness. I also have a Mk2 and had setup the screensaver mode under a Windows VM (was testing to see what all the Windows side had). I noticed when I plugged it in under Linux that same Windows screensaver image popped up. So some settings do definitely get saved with the Mk2. I'm going to also try disabling the Windows screensaver side to see if it works better with Linux as I mostly use Linux. The wakening below 20% dim also makes sense, now that I understand it.
