### ISSUE TITLE
Feature request: Dim light after inactivity

### ISSUE THREAD

**Issue by aenon83** [timothycrosley/streamdeck-ui#100] opened 2021-02-10 10:12 UTC
When using StreamDeck for Windows, there is an option to set an screensaver (just turns off the backlight) for a certain period of time.

For example, if you set 5 minutes, after that time passed without pressing any button, the light of the screen turns off and when you press any button the first time it just turn the light on again, and the second time executes the action.

Could it be possible to implement something like that?

**Comment by dodgyrabbit** [comment] 2021-03-30 02:53
Closing of duplicate of #7. 
Makes sense to do this, should not be too hard I think.

**Closed by dodgyrabbit** 2021-03-30 02:53 UTC
Labels: duplicate, enhancement
