### ISSUE TITLE
Streamdeck-ui cause OBS to hang in <defunct> status

### ISSUE THREAD

**Issue by tdcam** [timothycrosley/streamdeck-ui#259] opened 2022-09-07 01:58 UTC
I have used OBS under streamdeck-ui for many months. Recently, after an upgrade to Fedora 36, when I launch OBS from my Streamdeck, the obs process hangs:

   4523 tty2     Sl+    6:52              \_ /usr/bin/python3 /home/thomas.cameron/.local/bin/streamdeck --no-ui
   6712 tty2     Z+   185:25              |   \_ [obs] <defunct>

I can't kill the obs process, it's in Z state. 

If I kill the parent, obs exits and I can start OBS again. If not, it will restart from the command line, but I can't start the virtual camera.

This is probably something simple, but I'm drawing a blank as to what to do. Manually killing the streamdeck process kinda sucks. What am I missing? It used to work just fine.

**Comment by Data-007** [comment] 2022-09-07 03:38
There was an update V28 of OBS that caused some issues I think even with
the official windows Elgato software/device. Please see youtube and other
sources.

What version of OBS are you running?

**Comment by tdcam** [comment] 2022-09-07 13:06
I'm running obs-studio-27.2.4-4.fc36.x86_64, so not sure that's it.

**Comment by dodgyrabbit** [comment] 2022-09-18 17:22
I tried this in a VM, with Fedora 36 and was unable to reproduce. OBS can be closed normally. Closing as an unrelated issue to this project.

**Closed by dodgyrabbit** 2022-09-18 17:22 UTC
