### ISSUE TITLE
Make the "Open Image" dialog show the images instead of default icons

### ISSUE THREAD

**Issue by pblanton** [timothycrosley/streamdeck-ui#258] opened 2022-09-05 14:59 UTC
I am running Kubuntu 22.04 and when I am setting up a button on the StreamDeck and I click the [Image] button, the resulting dialog doesn't show the images. It just shows the stock image glyph ![image](https://user-images.githubusercontent.com/1143649/188477957-a13a0c44-2e55-4bf1-949d-5e2515c7e9aa.png).

![image](https://user-images.githubusercontent.com/1143649/188475882-1906d15b-e3fa-40e4-9868-b8e79d23cfc7.png)

I have tried the view buttons 

![image](https://user-images.githubusercontent.com/1143649/188477452-e9da2292-f82f-4f15-af6c-b84930035772.png)

but they don't work the way that they do in Dolphin.

What I'd like to see is the Icons View Mode (Ctrl+1) which shows the actual images the way Dolphin does. Here is the actual images in Icon View Mode in Dolphin...

![image](https://user-images.githubusercontent.com/1143649/188476792-739545f7-f031-4544-b8f2-2982974182e0.png)

It'd make it much easier to see what icon I am trying to find. As it is now, I have to have a separate Dolphin window open so I can see what the name of the desired icon is, then chose it by its name in the StreamDeck UI Open Image dialog.

It'd be great if you could support all three view modes that Dolphin does 

Icons View Mode (Ctrl+1)
![image](https://user-images.githubusercontent.com/1143649/188478267-b9b9445c-0924-44d4-87ba-ccd899f93ea3.png)

Compact View Mode (Ctrl+2)
![image](https://user-images.githubusercontent.com/1143649/188478175-386f720e-5075-4430-a300-990ab4181edb.png)

Details View Mode (Ctrl+3)
![image](https://user-images.githubusercontent.com/1143649/188478088-f6a409f4-c654-484e-90db-25c8708b2cef.png)

All three of which show the actual icons and not just stock image glyphs.

**Comment by dodgyrabbit** [comment] 2022-09-06 23:25
This is a duplicate of #256. Please see the comments there. https://github.com/timothycrosley/streamdeck-ui/issues/256#issuecomment-1236192797

**Closed by dodgyrabbit** 2022-09-06 23:25 UTC
Labels: enhancement
