### ISSUE TITLE
Unicode not rendering

### ISSUE THREAD

**Issue by 4ist** [timothycrosley/streamdeck-ui#85] opened 2020-12-27 01:32 UTC
I think this would be a valuable feature. Still new to this application.

**Comment by dyc3** [comment] 2020-12-27 21:12
Could you provide a screenshot of what you're referring to?

**Comment by Madcliff** [comment] 2020-12-31 11:42
I am having what I think is the same issue. When you insert a unicode character into the text box, the character itself will not be displayed when you press the key. I think this might be linked however to whatever keyboard layout you have selected.

**Comment by dodgyrabbit** [comment] 2021-03-28 03:58
Was unable to reproduce on latest master.
Still need to review this: https://github.com/moses-palmer/pynput/issues/187
Will try to reproduce more before closing.

**Comment by dodgyrabbit** [comment] 2021-03-28 17:19
I was unable to reproduce this problem in the current release or master. If someone can provide steps to reproduce, details on keyboard layout/language or other relevant details like operating system, please reopen. Thank you!

**Closed by dodgyrabbit** 2021-03-28 17:19 UTC
Labels: bug

**Comment by zefrawg** [comment] 2022-06-25 03:05
I am having the same problem, but have more detail. It only happens for some Unicode codepoints and it actually caused the write to abort completely at that point.

Whenever a character with a higher Unicode codepoint than U+16D6 is included in the 'write' section of a configured button, all text before this point will be written, all text after and including this point will not be written. (e.g. if the write section contains "Hello ᛝ World", when pressing the button "Hello " is written and error output is:

`Could not complete the write command: (6, 'ᛝ')`

I can verify it happens with U+16D7 through U+16DE but it failed with all the rest of the codepoints I randomly selected above U+16D6.
