### ISSUE TITLE
Streamdeck+ not recognized - even if udev rules contain vendor and product ID

### ISSUE THREAD

**Issue by gitemanuel** [timothycrosley/streamdeck-ui#283] opened 2022-12-14 00:10 UTC
When plugging in a new streamdeck+, streamdeck-ui does not recognize it. I then used udevadm to monitor the events on the interface - using first the streamdeck mk.2 (.0080) and then the streamdeck+ (.0084):

mk.2:
`UDEV  [502.683687] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0 (usb)
UDEV  [502.684172] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0080.0009 (hid)
UDEV  [502.684887] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0080.0009/input/input40 (input)
UDEV  [502.686093] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0080.0009/hidraw/hidraw5 (hidraw)
UDEV  [502.790333] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0080.0009/input/input40/event24 (input)
UDEV  [502.792085] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0080.0009 (hid)
UDEV  [502.793771] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0 (usb)
UDEV  [502.801541] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6 (usb)
`

streamdeck+:
`UDEV  [623.172260] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0 (usb)
UDEV  [623.172794] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0084.000A (hid)
UDEV  [623.173655] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0084.000A/input/input41 (input)
UDEV  [623.174698] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0084.000A/hidraw/hidraw5 (hidraw)
UDEV  [623.274238] add      /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0084.000A/input/input41/event24 (input)
UDEV  [623.275950] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:0FD9:0084.000A (hid)
UDEV  [623.278106] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0 (usb)
UDEV  [623.283813] bind     /devices/pci0000:00/0000:00:14.0/usb3/3-6 (usb)
`
I have tried to use both:
`SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", TAG+="uaccess"
`
and
`
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0084", TAG+="uaccess"
`

but neither have worked. I am willing to assist in any compatibility work that needs to be done :)

**Comment by LinuxGamesTV** [comment] 2022-12-14 04:24
It is not a bug.

The python elgato streamdeck don't know the Stream Deck+. It is a new device.

open a filemanager and go to: "$HOME/.local/lib/python3.10/site-packages/StreamDeck/". Open the ProductIDs.py and add this line "USB_PID_STREAMDECK_PLUS = 0x0084" after "USB_PID_STREAMDECK_MINI_MK2 = 0x0090".

Now try again, bu i think the Stream Deck+ is to new for the Linux Stream Deck Api.

**Comment by lundburgerr** [comment] 2023-01-30 17:24
I have the same issue.
Adding "USB_PID_STREAMDECK_PLUS = 0x0084" did not help. If I added "USB_PID_STREAMDECK_MINI_MK2 = 0x0084" streamdeck at least detects the device but I can't seem to do anything with it.

![Screenshot from 2023-01-30 12-23-12](https://user-images.githubusercontent.com/7665558/215549027-bd35d28e-7ec3-464a-aaa3-2bd64a1547a3.png)

**Comment by dodgyrabbit** [comment] 2023-02-24 04:30
Neither Stream Deck UI nor the [library that it uses](https://github.com/abcminiuser/python-elgato-streamdeck) currently supports streamdeck+ unfortunately. 

There is a work in progress to let the underlying library support it.
https://github.com/abcminiuser/python-elgato-streamdeck/pull/108

At minimum we should be able to get the button parts working.
No plans to add support for the new buttons, dials here unfortunately.

I'm closing this for now, but we can reopen once the upstream library has support.

**Closed by dodgyrabbit** 2023-02-24 04:30 UTC
Labels: wontfix

**Comment by Andrusowski** [comment] 2023-12-19 07:11
Hey, python-elgato-streamdeck now seems to support streamdeck+ 🎉
https://github.com/abcminiuser/python-elgato-streamdeck/commit/56f91960297f753acdaeb79fd460c4326f7c4840

**Comment by Simon99de** [comment] 2024-01-07 21:18
It looks like/ The description says that Streamdeck+ is supported.

Will there be a compatibility update for Streamdeck+ when there is time?
