### ISSUE TITLE
can not open from time to time

### ISSUE THREAD

**Issue by sevku** [timothycrosley/streamdeck-ui#11] opened 2019-11-08 12:20 UTC
`Traceback (most recent call last):
  File "/usr/local/bin/streamdeck", line 10, in <module>
    sys.exit(start())
  File "/usr/local/lib/python3.7/dist-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/usr/local/lib/python3.7/dist-packages/streamdeck_ui/api.py", line 100, in open_decks
    deck.open()
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Devices/StreamDeck.py", line 114, in open
    self.device.open()
  File "/usr/local/lib/python3.7/dist-packages/StreamDeck/Transport/HIDAPI.py", line 51, in open
    self.hid.open_path(self.hid_info['path'])
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed
`

**Comment by sevku** [comment] 2019-11-08 13:16
Seems like this has already been reported in #8

**Comment by dodgyrabbit** [comment] 2021-03-22 18:08
Duplicate of #8

**Closed by dodgyrabbit** 2021-03-22 18:08 UTC
Labels: duplicate
