### ISSUE TITLE
No method to close streamdeck-ui in i3

### ISSUE THREAD

**Issue by Madcliff** [timothycrosley/streamdeck-ui#86] opened 2020-12-31 12:04 UTC
I need to kill the process to be able to close the application when using I3.

**Comment by marcnnn** [comment] 2021-02-26 13:47
It installs a tray so you can close streamdeck-ui when you close the tray as well.
If you don't have install tray support this could be the Problem?

**Comment by tylerjw** [comment] 2021-03-17 20:34
I've used `killall streamdeck` for stopping it in i3.  I actually really like that it goes into the background when you "quit" it and is in the tray.

**Comment by dodgyrabbit** [comment] 2021-03-22 16:36
As per @marcnnn you should be able to gracefully exit, click on the tray icon->Exit.
If you have more details on specifics on I3 and why this won't work, please feel free to reopen.
Closing the main Window does not exit the application "by design".

**Closed by dodgyrabbit** 2021-03-22 16:36 UTC
Labels: wontfix
