### ISSUE TITLE
programs launched become defunct until the streamdeck-ui is closed

### ISSUE THREAD

**Issue by avalitan** [timothycrosley/streamdeck-ui#92] opened 2021-01-05 17:55 UTC
Programs launched by the streamdeck and closed become defunct until the streamdeck-ui is closed.

I have made a workaround/fix, will submit it trough a pull request!

**Comment by dodgyrabbit** [comment] 2021-03-26 22:02
Hi @avalitan  - are you able to provide some details on how to reproduce, which OS etc. ?
From my own testing - the processes launched are not linked to the parent process.
If possible, please pull the latest master and test with that.

**Comment by delpes** [comment] 2021-04-02 12:30
I tried this on **arch** with two buttons:

1: Command: notepadqq
2: Command: killall notepadqq-bin

Opening and closing the program with the Stream Deck Buttons worked fine.
Opening with Stream Deck and closing the program via its own menu worked also fine.

I had no problem using any other buttons after the program was opened or closed via Stream Deck

I am on version **1.0.4**

**Comment by dodgyrabbit** [comment] 2021-04-21 02:31
Been unable to reproduce this issue. It may be related to bugs present in older versions. 
Closing, feel free to open again with more detailed steps on how to reproduce.

**Closed by dodgyrabbit** 2021-04-21 02:31 UTC
Labels: bug
