### ISSUE TITLE
I have reinstalled my machine (after faulty graphics card upgrade).

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#186] opened 2022-01-08 13:14 UTC
I have reinstalled my machine (after faulty graphics card upgrade).
I find that its impossible to install from arch repo's...... and installing from source I get

ERROR: Package 'streamdeck-ui' requires a different Python: 3.10.1 not in '<3.10,>=3.8'

I need streamdeck any chance of uping your python level?

_Originally posted by @Data-007 in https://github.com/timothycrosley/streamdeck-ui/issues/173#issuecomment-1007987029_

**Comment by Tylermarques** [comment] 2022-01-13 03:34
@Data-007 You should try installing python 3.9. The response is telling you that python 3.10.1 is too new for this application.

**Comment by Data-007** [comment] 2022-02-01 17:57
Hi 
Another reinstall, I have downgraded python. However I am unable to run up my streamdeck.
the error I get this time,
[steve@steve-Main ~]$ streamdeck
FATA[0000] Unable to open StreamDeck connection          error="Unable to open device: permission denied"

I have tried unplugging the streamdeck and re-plugging it in still the same.

What a ta do? This is on arch based distro, what packages from the aur should be installed?
I have installed or rather tried to install from source to but to no avail.  Can some one help?
Steve.

**Comment by dodgyrabbit** [comment] 2022-02-01 22:08
I found a similar issue [here](https://github.com/abcminiuser/python-elgato-streamdeck/issues/79), but besides reinstalling - it's not clear what the root cause was.

Double check that this was done correctly (the udev rules):
https://github.com/timothycrosley/streamdeck-ui#manual-installation

You could also review the output of `dmesg` right after you plug the streamdeck in. It may provide some clues.

**Comment by Data-007** [comment] 2022-02-02 03:23
> I found a similar issue [here](https://github.com/abcminiuser/python-elgato-streamdeck/issues/79), but besides reinstalling - it's not clear what the root cause was.
> 
> Double check that this was done correctly (the udev rules): https://github.com/timothycrosley/streamdeck-ui#manual-installation
> 
> You could also review the output of `dmesg` right after you plug the streamdeck in. It may provide some clues.

  972.578391] usb 1-4: USB disconnect, device number 3
[  976.587370] usb 1-4: new high-speed USB device number 5 using xhci_hcd
[  976.758070] usb 1-4: New USB device found, idVendor=0fd9, idProduct=006c, bcdDevice= 2.00
[  976.758073] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  976.758074] usb 1-4: Product: Stream Deck XL
[  976.758075] usb 1-4: Manufacturer: Elgato
[  976.758076] usb 1-4: SerialNumber: CL08K1A01522
[  976.782210] input: Elgato Stream Deck XL as /devices/pci0000:00/0000:00:01.3/0000:02:00.0/usb1/1-4/1-4:1.0/0003:0FD9:006C.0007/input/input24
[  976.837405] hid-generic 0003:0FD9:006C.0007: input,hidraw4: USB HID v1.10 Device [Elgato Stream Deck XL] on usb-0000:02:00.0-4/input0
[ 1043.181546] input: GoUinputDevice as /devices/virtual/input/input25

**Comment by dodgyrabbit** [comment] 2022-02-02 04:38
I suspect somehow the udev rule is not working. We can troubleshoot that, which can be a bit complex. 
However, you could do the following as a next step. 

Review the files in `/etc/udev/rules.d/`. You should have a file called `70-streamdeck.rules` (the one you created [here](https://github.com/timothycrosley/streamdeck-ui#manual-installation)). You can rename (or delete and recreate) that file to `99-streamdeck.rules`. You will need to be `sudo` for that.  The files are processed in lexical order, so files with higher numbers can override lower number rules. There could be something "above" your current file that stops the rule from working properly.

Once complete
```
sudo udevadm control --reload-rules
```
Lastly, unplug and replug. You could also reboot just to be sure there are no other udev rules that could affect things.

**Comment by Data-007** [comment] 2022-02-02 05:01
[steve@steve-Main rules.d]$ ls -la
total 72
drwxr-xr-x 2 root root  4096 Feb  2 04:18 .
drwxr-xr-x 4 root root  4096 Feb  2 03:56 ..
-rw-r--r-- 1 root root   733 Feb  2 04:18 70-snap.nordpass.rules
-rw-r--r-- 1 root root 59395 Feb  2 04:17 70-snap.snapd.rules
[steve@steve-Main rules.d]$ streamdeck
bash: streamdeck: command not found
[steve@steve-Main rules.d]$ pip3 install git+https://github.com/timotycrosley/streamdeck-ui
Traceback (most recent call last):
  File "/usr/bin/pip3", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip3')())
  File "/usr/bin/pip3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip

**Comment by dodgyrabbit** [comment] 2022-02-02 14:49
Steve based on the output it sounds like you have two issues. You have not configured the udev rules _and_ you're having trouble installing streamdeck. Note that the udev rules are not automatically created, you have to do it.

I don't use Arch but in my previous testing I had to install these:
```
sudo pacman -S python-pip gcc
sudo pacman -S hidapi
```

Then follow [these steps](https://github.com/timothycrosley/streamdeck-ui#manual-installation) exactly:
![image](https://user-images.githubusercontent.com/518187/152176765-ca798fe0-d4f5-45df-813f-a1637b2df414.png)

Good luck!

**Comment by Data-007** [comment] 2022-02-02 15:53
Hi Thanks Pieter.
I only have one small problem now the auto start of streamdeck.
If I fire up the cli and type streamdeck  streamdeck runs. However
it tie's up the cli if I close the cli then streamdeck ui, closes.

Previously I have been able to set it to run at startup, using an application the ArcolinuxTweakTool has/HAD a 
way to launch streamdeck at startup, however its not working this time.

Did you not yourself mark the -n reference as not working/Bug?

Your thoughts Pieter.

**Comment by dodgyrabbit** [comment] 2022-02-02 17:59
The `-n` option just avoids the UI popping up on startup, but does not solve the cli issue. There is a PR open and another case to allow this to run under systemd, which may be the better solution. Hopefully I get time to review that at some point - but for the moment I'm just trying to catch up on this project a bit first before tackling new features. Thanks, I'm closing this case as it sounds like the original issue is resolved.

**Closed by dodgyrabbit** 2022-02-02 17:59 UTC
Labels: question

**Comment by Tylermarques** [comment] 2022-02-02 18:49
@Data-007 I have streamdeck set to open on startup using GNOME's startup applications. If that isn't applicable to you, you can always use `nohup` in combination with `&`. 

The command you would run is as follows:
```
nohup streamdeck & 
```

`nohup` is a command that takes all of the output of the command you are trying to run and pipes it to `nohup.out` file in the directory you run the command from. `nohup` also ensures that when the terminal closes, `streamdeck` won't close as well. 

[This should explain any other questions about the command you might have. ](https://linuxize.com/post/how-to-run-linux-commands-in-background/)
